### PR TITLE
Refactor to help understand how it works

### PR DESCRIPTION
**Pull request by keith-hall**
Tests still pass after refactor, so hopefully nothing is broken.

### CODE REVIEW

**Comment by keith-hall** [comment]
I'm not a user of this plugin myself, so waiting for someone to test this branch out and say it's fine before merging. I guess we'll need to update Package Control to point this package to this repo after we get some contributors. i.e. it could become the new/supported fork if it gets some interest.

**Comment by reagle** [comment]
I use this plug-in, but I'm not sure who is in charge of this repository. It's been six months, and nothing has happened…?

Is there any easy way to install a plug in via a GitHub merge request? If so, I can give it a go.

**Comment by keith-hall** [comment]
Did you try in the ST command palette: `Package Control: Add Repository` with the url of this PR branch: `https://github.com/SublimeText/SublimeTableEditor/tree/refactor`?

**Comment by reagle** [comment]
Thanks, I installed it and tested it against [test-tables.md](https://reagle.org/joseph/2016/min-eg/test-tables.md) and it seems to work as well as the old one.

**Comment by reagle** [comment]
I suspect folks won't even know this fork exists if you don't point package control here. On the README and description it could say this package is unmaintained and looking for contribs.

**Comment by CodeByZach** [comment]
Could not find an Issues section so adding this here:

**Please link the version in Package Control** at https://packagecontrol.io/packages/Table%20Editor **to this repo** rather than the depreciated one.

**Comment by FichteFoll** [comment]
FYI, I have initiated a takeover of this package: https://github.com/wbond/package_control_channel/pull/9199

**Pull request merged**
